spring.application.name=ledger
spring.datasource.url=jdbc:postgresql://localhost:5433/ledger_db
spring.datasource.username=ledger_admin
spring.datasource.password=ledger1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.structured.format.console=ecs