spring.application.name=ledger
spring.datasource.url=jdbc:postgresql://localhost:5433/ledger_db
spring.datasource.username=ledger_admin
spring.datasource.password=ledger1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.structured.format.console=ecs